# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 14:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_wolfpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wolfpage',
            options={'verbose_name_plural': 'Wolfhound Pages'},
        ),
    ]
