# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20160721_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='first_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='friend',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='friend',
            name='last_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
