# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-19 01:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20160721_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='url',
        ),
        migrations.RemoveField(
            model_name='question',
            name='url',
        ),
        migrations.RemoveField(
            model_name='showdown',
            name='url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='custom_data',
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='showdown',
            name='loser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loses', to='api.Friend'),
        ),
        migrations.AlterField(
            model_name='showdown',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wins', to='api.Friend'),
        ),
        migrations.DeleteModel(
            name='Candidate',
        ),
    ]
