# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-19 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20160819_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='custom_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
