# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-19 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_user_custom_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='invite_friend_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='friend',
            name='facebook_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
